version: '3.11'

services:
  scrapy:
    build:
      context: .
      dockerfile: dockerfile  # Replace with your actual Dockerfile name
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: mohammadmirzaei
      POSTGRES_PASSWORD: your_password  # Replace with your actual password
      POSTGRES_DB: jobProject
